### PR TITLE
Invite friend

### PR DESCRIPTION
**Pull request by nottoobright**
Task: https://trello.com/c/NRfFsGN3/1-friends-invitation

How does it work?
Since the front-end form is not yet ready, invite friends like this: localhost:3001/invite?email=yourfriendemail

Test it using postman and keep the server on. You should see the email link as a response either on postman or on the console.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
@nottoobright  Looking briefly Your code is not prettified.

**Comment by belyas** [comment]
@nottoobright Hmmm I think you've forgotten to expose your api endpoint to be accessed `Cannot GET /invite`.

Also in the routes folder, the `index.js` meant to expose other routes and not having a specific route implementation, so for your invite route I may go with creating a `friends.js` where I put this logic as it's related to friend and I can use `index.js` to expose both `friends.js` and `users.js` so I can require only `const routes = require('./routes');` in the `server.js` file. then change any needed parts as `users endpoint` then add your new endpoint.

I don't know why did you use EEFI in `/invite endpoint`?? you can only place `async` before ` (req, res) => {` like this `sync  (req, res) => {` and remove this effy as the endoint is already wrapped within a function and not exposed globally.

I think that's all I've got for now. Good luck.

**Comment by nottoobright** [comment]
@belyas - Alright, I'll do the changes and then commit

**Review by belyas — COMMENTED** [review]
@nottoobright  All right, Good luck

**Comment by nottoobright** [comment]
@belyas - Did the changes you requested. Please review

**Comment by belyas** [comment]
@nottoobright yes looks better even if you can centralize things in index.js file and would be the only entry points to routes, but that's fine for now, also I observed something is that the sending emails has nothing to in routes, I've seen this implemented in other files as well which is not great as it should be abstracted. in a service or a helper function as. it's not part of that functionality, also if you have to change the module later, you'll have to change every file as this is very redudant and must be avoided, so create a servicer/helper that handles sending emails would be much better. 

I don't think if you have checked the linting of your code to see if everything is following the style guide.

Good luck

**Comment by nottoobright** [comment]
@belyas - I thought of that too when I first started writing code for emails but every email is different in terms of its content. So I could not make a helper function. I'll still look into it if I can find something common to be put in a single helper function and do that.

Also, yes, I forgot to run the lint again. Will do that in my next commit.

**Comment by belyas** [comment]
@nottoobright I don't think so, the nodemailer params are the same, for the transport you have some params to pass to the helper function, and the same sending email helper function that will take as params e.g. `(sender_email, message)` or any other standard params, you can pass an object so it would be easy to add more params if this module is changed by another email service.

Hope I'm clear. Good luck

**Comment by nottoobright** [comment]
@belyas - Added the email controller. Please check and confirm. Check 1st comment to test it out.

**Comment by belyas** [comment]
@nottoobright Good move, but I've got two more issues wiht this:
  
  1> the email helper should not be in controllers folder as it's not a controller, you can move it to a utils. folder to be reused throughout the app

  2> `.sendEmail` should be a helper function as well and it takes inputs and return an output

I think that's it and you'ra all good to go, and don't forget to test the code style by linter.

Thannks and good work

**Comment by nottoobright** [comment]
@belyas - I'll move it to the utils folder and push again, but I didn't get your second point. Could you elaborate as to what I should do?

**Comment by belyas** [comment]
@nottoobright sorry my bad, just got confused it's ok now things look better, Thanks

@ArnasDickus if you can merge this PR as I think it's good if you don't have any other concerns.

**Comment by ArnasDickus** [comment]
Alright, thanks for quick response @belyas, and congratulation @nottoobright for finally finishing this task.

Although one concern: @nottoobright Why do you add pull requests working from a master branch instead of creating a branch from dev branch, and working on that branch? Anyways since that does not affect the code. I'm merging it.

**Comment by nottoobright** [comment]
@ArnasDickus - I do that just as a convenience, nothing really else to it. I can merge using a separate dev branch if needed that is, but it's just an extra step in the process.

**Comment by ArnasDickus** [comment]
@nottoobright It doesn't affect the code in any way So you can do it however you want. I was just curious about it.

**Pull request merged**
