### PR TITLE
cleaned up codebase

### PR DESCRIPTION
**Pull request by belyas**
Trello card: https://trello.com/c/lMk7LvKH/114-clean-up-back-end

I removed some files such as route index.js and config passport.js as they no longer have any meaning also removed these packages `bcrypt, crypto, express-session, passport, passport-local` and added new env variable name `JWT_SECRET` the .env.example file is updated to copy the variable and you're free to change its key value.

### CODE REVIEW

**Comment by nottoobright** [comment]
@belyas - Some of these packages like brcypt and crypto will break the app if not present. You suggested to instead use bcryptjs as it is more secure. So do we add it in this task itself or make it a new one to fix it?

**Comment by belyas** [comment]
@nottoobright crypto is a node built-in package [have a look here](https://nodejs.org/api/crypto.html) for bcrypt we've already got bcryptjs, so nothing will be broken I believe, and I also removed their calls from files, I think this was only from user.js route file.

**Comment by mubarakshow** [comment]
@belyas I tried to run the code, but I got this error. 
backend pr5 error

**Comment by belyas** [comment]
@mubarakshow do you have `.env` file setup correctly? if not have a look at [env.example](https://github.com/belyas/mappypals_backend/blob/dev/env.example) just rename it to `.env` and replace the url with yours

**Comment by nottoobright** [comment]
@mubarakshow - It's most prob because your .env variable is not a string. Make sure it is inside quotes

**Comment by ArnasDickus** [comment]
So if @nottoobright concerns have been put to rest, I can merge it. Regarding Mubarakshow. His problem was running project without creating .env file.

**Pull request merged**
