### PR TITLE
Email already exists - Added end point for error checker

### PR DESCRIPTION
**Pull request by danielgnz**
Created a new end point /validate-email which is used by the front-end to check if email already exists in database during registration.

### CODE REVIEW

**Review by belyas — COMMENTED** [review]
Hi @danielgnz Thanks for the good work.

I've got some issues with this:

1. please clean up the controller no console logs and return a json response error on the catch block

2. User the endpoint in the user router instead of using it server.js file.

Try to check also the linter and prettier for coding style.

**Comment by danielgnz** [comment]
If I use the endpoint in the user router, I will get a 404 error: POST / Not Found... Do you have any idea how to fix that?

**Comment by danielgnz** [comment]
**users.js**
image

**userController.js**
image

**Server Response**
image

**Error**
image

**Comment by belyas** [comment]
> **users.js**
> image
> 
> **userController.js**
> image
> 
> **Server Response**
> image
> 
> **Error**
> image

Yeah sure, because you need to prefix the url by `/users`

**Comment by danielgnz** [comment]
Thank you @belyas. Everything works fine now.

I have implemented all the changes suggested by you.

**Comment by ArnasDickus** [comment]
I didn't see any problems. And since you added fixed suggested by @belyas I approve it. From my understanding, this PR is for this task -
<https://trello.com/c/eXsEPkXb/165-display-error-if-email-in-use-signupjs>

**Pull request merged**
