### PR TITLE
separation of concerns

### PR DESCRIPTION
**Pull request by dgovnor**
Task:
1) Create 4 folders middlewares, controllers, models and routes.
2) Add functionality All the logic can be in the controller, all validations in the middleware, all endpoint in the route and DB in models.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
@dgovnor One thing I noticed. Next time you should add smaller commits, instead of having one large commit. It makes reviewing easier. [Example](https://github.com/zero-to-mastery/mappypals_backend/pull/15)

**Comment by dgovnor** [comment]
> @dgovnor One thing I noticed. Next time you should add smaller commits, instead of having one large commit. It makes reviewing easier. [Example](https://github.com/zero-to-mastery/mappypals_backend/pull/15)

Very sorry I have learnt that now

**Review by belyas — COMMENTED** [review]
Hello @dgovnor 

Thanks for the idea of separating concerns which makes a lot of sense.

I'm with @ArnasDickus about making commits smaller and they should be related to one thing so that we can follow what's being happening easily now it's hard to track your changes you know. 

I'd like to know what the `/auth` folder is about, please?

in `Controllers` try to omit those comments, we know that the FriendController is meant to have friend related endpoints, same for user.

Try to name controllers in singular not plural please e.g `FriendController` instead of `FriendsController` and same for user controller.

It would also be nice if we have one centralized file `index.js` per folder to export from, if this technique is new for you just ignore it for now, we can see this later on.

The middleware folder is not a separation of concerns because it has a file called `middleware.js` which doesn't make sense actually, I'd rather name it `authMiddleware.js` and put only auth related validation.

Try to fix coding styles by using this command on your root folder of the project `npm run dev:lint` it will list you some warnings/errors to be fixed,. normally the command will fix what it can but if there are some remaining erros/warning please try to fix them then commit again.

**Comment by dgovnor** [comment]
> Hello @dgovnor
> 
> Thanks for the idea of separating concerns which makes a lot of sense.
> 
> I'm with @ArnasDickus about making commits smaller and they should be related to one thing so that we can follow what's being happening easily now it's hard to track your changes you know.
> 
> I'd like to know what the `/auth` folder is about, please?
> 
> in `Controllers` try to omit those comments, we know that the FriendController is meant to have friend related endpoints, same for user.
> 
> Try to name controllers in singular not plural please e.g `FriendController` instead of `FriendsController` and same for user controller.
> 
> It would also be nice if we have one centralized file `index.js` per folder to export from, if this technique is new for you just ignore it for now, we can see this later on.
> 
> The middleware folder is not a separation of concerns because it has a file called `middleware.js` which doesn't make sense actually, I'd rather name it `authMiddleware.js` and put only auth related validation.
> 
> Try to fix coding styles by using this command on your root folder of the project `npm run dev:lint` it will list you some warnings/errors to be fixed,. normally the command will fix what it can but if there are some remaining erros/warning please try to fix them then commit again.

Thanks for your feedback and would work towards it, but let me clear somethings too.
the auth folder is empty but that should be where the authentication and authorization eg jwt, bcrypt etc.

The middleware folder was created to contain all validations, I wasn't the one who created the middleware.js file I only moved it from the config folder as it has nothing to do there, I will also rename it as you have suggested though, but looking at the code base the middleware.js was never used I couldn't delete it as I don't know where it was written maybe for future use.

Concerning the coding style am using, Eslint extension which helps to correct any wrong coding style.

In all I will make all the necessary corrections and commit again. Thanks.

**Comment by belyas** [comment]
Thanks @dgovnor I think you'd better fix the code styling within this branch as it's a related work, you don't need to create a new branch to fix code styling, makes more sense.

**Comment by ArnasDickus** [comment]
Hello, @dgovnor Talked with @belyas everything works. Approving it now. For some reason, he don't have access to merge it.

**Pull request merged**
