### PR TITLE
Implemented JWT to protect resources

### PR DESCRIPTION
**Pull request by belyas**
This PR added protecting resources by implementing json web token.

I added a middleware which checks if the sent token is valid or not, if not, returns an error message, if valid token return the requested resource, for now I created a simple resource to check against using postman.

The back end needs some clean up though as some packages are no longer useful such as: passport, passport-local, express-session, async, bcrypt, crypto.

### CODE REVIEW

**Comment by nottoobright** [comment]
Upon review, I have these suggestions:

1) You don't need to return res.status().json() - res itself stop code execution so it's redundant to return that.
2) Why were the db details changed?
3) The app.get('/private') in server.js is just for testing right? Did you forget to remove it?
4) You mention async and bcrypt and useless dependencies but they are both uses in sending emails and hashing passwords respectively.

**Comment by belyas** [comment]
Alright, I created this end point to check if everything's working:
```
// server.js
app.get('/private', isAuthenticated, (req, res) =>  {
    return res.status(200).json({ message: 'Private message revealed!' });
});
```
if you try to access to it, you'll get Not authenticated error message
Here's the login request in Curl
```
curl -X POST \
  http://127.0.0.1:3001/users/login \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: ef238771-1f56-4b6c-a825-9e707bc016e6' \
  -H 'cache-control: no-cache' \
  -d '{
    "email": "youremail@gmail.com",
    "password": "yourpassword"
}'
```
you'll get back a token and userId if your emails\password exists.

You can then use token to get access to the protected resource, Curl example:

```
curl -X GET \
  http://127.0.0.1:3001/private \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9........' \
  -H 'Postman-Token: e63f32ec-f1a5-4bac-a06e-67cdaa842bae' \
  -H 'cache-control: no-cache'

```

If token is valid, you'll get a response from the resource otherwise an error message.

**Comment by belyas** [comment]
> Upon review, I have these suggestions:
> 
> 1. You don't need to return res.status().json() - res itself stop code execution so it's redundant to return that.
> 2. Why were the db details changed?
> 3. The app.get('/private') in server.js is just for testing right? Did you forget to remove it?
> 4. You mention async and bcrypt and useless dependencies but they are both uses in sending emails and hashing passwords respectively.

- I don't think `res.status().json()` is topping the execution of the code, we need to return it actually otherwise if we're inside an if block, the code will go on to the bottom if we don't return.

- I have my own db details actually, or should I test with the old ones? sorry. This is why I was talking about .env file and each one has their own proper variables.

- Yes app.get('/private') is only for testing purpose, I left it there so you can test it and things are working as I don't see any protected resources for now, that's why I created that to test against.

- Yes indeed, async is already exists in ES7 a feature, for bcrypt we have bcryptjs which is a better version of bcrypt, also we don't need crypto as it has performance issue and we can use the bcryptjs to generate the salt and hash for signing up.

NOTE: I see that User model has token and expirsein, doesn't make sense as these fields have nothing to do there, unless for me.

**Comment by nottoobright** [comment]
1. Yeah, don't change the db details. If it works with yours, it'll work with ours too. You need to login with 
    the details pinned on the discord channel and then whitelist your IP to access it though.
2) I'm using async.waterfall which I'm pretty sure is not a native feature. Still will have a look at it.
3) The User model has token and expiresin because it is used for confirming account creation and for reset password too.

**Comment by belyas** [comment]
I see but the issue is that I have a dynamic IP address, so it won't work for me, but I don't feel like I have to use the same db, I think each dev should have their own URIs, I'm insisting to have .env file and which makes more sense rather obliged to use same db.

I  don't know what that async.waterfall does but thought async is for promises which is natively supported.

I think User should not be aware of those fields though, they should be delegated to their own documents: user_confirm, user_reset something like that.

**Comment by nottoobright** [comment]
Okay, there are two solutions:
1) We create a .env file for everyone to recreate.
2) Every dev uses their own db but adds db config file in .gitignore so it doesn't get commited in every PR.

And, the User technically is never aware of his model at all right? There's no method to retrieve it too. Unless our server is compromised, it's safe. Also, we're currently working towards P0 (MVP), so little optimizations can be worked on, but not high priority.

**Comment by belyas** [comment]
Yes .env file to be created, as mentioned before on discord, we will create .env.example to copy the environment variable available and this file which will be updated each time we add new environment variable.

No we won't ignore db file, why should we? this file will be dynamic as we'll only give it the name of the enviroment variable name, so nothing static will be put there, hope you get it.

By the way, I reverted back the db URI.

**Comment by nottoobright** [comment]
Uh, I got what you said, but my solutions weren't mutually exclusive. They were either 1) or 2). 

I already have a .env file of my own for the Google stuff I was trying so I have no prob using it. Push in a .env.example with it as well if you want. It's too small a task to have its own PR.

**Comment by belyas** [comment]
@nottoobright It's done, env.example file was created, each dev now can has their own version of env file with same variables and with their own keys.

I also removed the test end point '/private', I tested the login on the front end, I can clearly see that the token is returned once login was successful.

Some clean up will be done later but the core functionality is now working fine.

**Review by nottoobright — APPROVED** [review]
Everything works alright. Just one thing that you missed. 
 `    if (!req.user.active) {
        res.status(401).json({ error: 'Please confirm your account before logging in' })
    }`
This check is necessary to confirm that the account was confirmed using email and cannot login before that. Everything else seems to work properly. Good work.

**Comment by belyas** [comment]
Done, sorry didn't pay attention to this.

**Comment by ArnasDickus** [comment]
Since @nottoobright review it. I'am going to merge it.

**Pull request merged**
