### PR TITLE
Confirm email before account is created added - Backend only.

### PR DESCRIPTION
**Pull request by nottoobright**
Result of the conversation that happened here between me and @ArnasDickus: https://trello.com/c/Uy93sgS1/89-fix-register-login-back-end

1) The user now registers, an active flag is set to false by default.
2) Is sent an email to confirm
3) Without confirming, cannot log in
4) Once confirmed, the token is deleted and an active flag is set to true.

Note: The front-end for this is yet to be made. I'm waiting for [this](https://github.com/zero-to-mastery/mappypals/pull/68) to be merged first.

Some other random optimization changes also done to make the code more readable and less repetitive.

### CODE REVIEW

**Comment by mubarakshow** [comment]
@nottoobright here is my review
1. express wasn't included in the package.json file. I had to install it myself. 
- Please update that. 

2. I get this error whenever i ```npm start```. 
server-error

**Comment by nottoobright** [comment]
1) Alright. Done.

2) You need to whitelist your IP to be able to connect to the database
Give me your IP (If it's static) so I can whitelist it
OR - go to this link: https://cloud.mongodb.com/v2/5cb88e8fff7a254293b0d1ef#clusters/security/whitelist

And login using the id and pass pinned in the discord channel. Then click on all current IP address and try again
If the error persists, ping me

**Comment by ArnasDickus** [comment]
Reviewing pull request.
Please note that  this pull request needs to be reviewed with front-end pull request together.
https://github.com/zero-to-mastery/mappypals/pull/68

**Comment by ArnasDickus** [comment]
So after talking with  @nottoobright turns out. I needed to use fake emails for it to work. Not real ones due to cost issue. Using ethereal everything seems to work.
Register - works add's items to mongo database.
Login - works if manually change in mongoDB active from false to true.
Reset password - works using Etheral email.

**Pull request merged**
