### PR TITLE
added eslint + prettier

### PR DESCRIPTION
**Pull request by belyas**
[Trello card](https://trello.com/c/8D5umD6O/116-add-eslint-and-prettier-styling)

The CLI to use these commands are:

**Prettier:** 
`npm run dev:format`

**Eslint:**
`npm run dev:lint`

for `prettier` my favourite hack is on save the code is auto-formatted for me, in vscode editor follow these steps:
`Settings -> Text editor -> Formatting -> check 'Format on save' option`

### CODE REVIEW

**Comment by ArnasDickus** [comment]
I try to review it.

**Comment by ArnasDickus** [comment]
Hello, @belyas  I can't run the commands, for some reason. Do you need to install something globally first?
mappypals-error

**Comment by belyas** [comment]
@ArnasDickus have you installed the new dependencies? eslint and prettier and their plugins? they're on the packacge.json file

**Comment by ArnasDickus** [comment]
@belyas 
1) I downloaded your project. 
2) wrote `npm install`
3) Fix .env file issues
4) Tried to run these commands.
I'am going to request review from nottoobright. Maybe this is my hardware problem.

**Comment by belyas** [comment]
@ArnasDickus can you please change the command:
`"dev:format": "prettier --write './**/*.js'"` to `"dev:format": "./node_modules/.bin/prettier --write './**/*.js'"`

just to make sure of something, if this is not working, something wrong with your installation

**Comment by ArnasDickus** [comment]
Didn't worked. Also removing . Would also give me an error.
add-eslint-error

**Comment by belyas** [comment]
@ArnasDickus it works fine for me though with both methods I mean with only `prettier` or `./node_modules/.bin/prettier`

Screen Shot 2019-05-22 at 19 35 49

**Comment by belyas** [comment]
@ArnasDickus I noticed that you're using Windows, maybe that's the issue? I'm using Mac OS, just thought so, but certainly you've got something wrong on your machine.

**Review by nottoobright — CHANGES_REQUESTED** [review]
The `"dev:lint": "eslint --fix ."` command works fine. But I could not get the `"dev:format": "./node_modules/.bin/prettier --write './**/*.js'"` to work even after your suggested changed @belyas. I tested on Windows too. Can cross-check on Linux in a while if required

**Comment by belyas** [comment]
@nottoobright try to remove the `node_modules` folder and launch `npm install` and see because I think you don't have prettier binary so maybe it wasn't installed as a dependebcy.

**Comment by nottoobright** [comment]
@belyas - Tried it. Didn't work

**Comment by belyas** [comment]
@nottoobright it's a windows issue actually, it should be fixed now, can you please guys try now? @ArnasDickus

**Comment by ArnasDickus** [comment]
I check it out. "dev:format" command works properly. dev:lint for me still does not work, but since its works, for @nottoobright we concluded that it's my machine problem and not your code.

So, in conclusion, good work. I'm merging it.

**Comment by belyas** [comment]
Thanks @ArnasDickus

**Comment by fuckupc** [comment]
@belyas @ArnasDickus  This problem is because **Windows** cannot recognize **Single Quotation Marks** in its comand line. We can fix this by replacing **single quote** by  **backslash + double quotes**, which I already installed in my last [Pull Request](https://github.com/zero-to-mastery/mappypals/pull/79).
捕获

**Comment by belyas** [comment]
@fuckupc yes that's true, it's a Windows os issue, it's already done though Thanks for your feedback.

**Pull request merged**
